Modified entry point

diff --git a/7.2/alpine3.8/fpm/docker-php-entrypoint b/7.2/alpine3.8/fpm/docker-php-entrypoint
--- a/7.2/alpine3.8/fpm/docker-php-entrypoint
+++ b/7.2/alpine3.8/fpm/docker-php-entrypoint
@@ -6,31 +6,34 @@ if [ "${1#-}" != "$1" ]; then
 	set -- php-fpm "$@"
 fi
 
-[[ "z${USER_ID}" == "z" ]] && USER_ID=$(id -u)
-[[ "z${GROUP_ID}" == "z" ]] && GROUP_ID=$(id -g)
+#[[ "z${USER_ID}" == "z" ]] && USER_ID=$(id -u)
+: ${USER_ID:=$(id -u)}
+
 
 if [[ ${USER_ID} -eq $(id -u) ]];then
     exec "$@"
 elif [[ $(id -u) -eq 0 ]]; then
     RUN_USER=${USER_NAME:=runuser}
-    RUN_GROUP=$(getent group|awk -F: '$3=='${GROUP_ID}'{print $1}')
+    RUN_GROUP=${GROUP_NAME:=rungroup}
+    #RUN_GROUP=$(getent group|awk -F: '$3=='${GROUP_ID}'{print $1}')
 
-    if [ "z${RUN_GROUP}" == "z" ];then
-        RUN_GROUP=${GROUP_NAME:=rungroup}
-        addgroup -g ${GROUP_ID} ${RUN_GROUP}
+    if [[ -n "${GROUP_ID}" ]]; then
+      addgroup -g ${GROUP_ID} ${RUN_GROUP}
+    else
+      addgroup ${RUN_GROUP}
     fi
-
     adduser -s /bin/sh -u ${USER_ID} -G ${RUN_GROUP} -D -S ${RUN_USER}
 
     # Give user write access to app files
     chown ${RUN_USER}:${RUN_GROUP} -R .
-    
-    #Add access to default file descriptors
-    chmod +w /dev/stderr /dev/stdout
-    chmod +r /dev/stdin
 
-    exec sudo -E -u "${RUN_USER}" "$@"
+cat > /usr/local/etc/php-fpm.d/zz-docker-user.conf <<EOF
+[www]
+user = ${RUN_USER}
+group = ${RUN_GROUP}
+EOF
+    exec "$@"
 else
-  echo "Cannot run sudo as unprivileged user" >&2
+  echo "Cannot run add users as unprivileged user" >&2
 fi
 
